version: 1.0.{build}
os: Visual Studio 2015
environment:
  MADB_PFX_KEY:
    secure: FJBT+POuE4uUdLGJRsmNsw==
  VS_PFX_KEY: VS_KEY_B73CFF62431D23D3
install:
- choco install -y ilmerge
- set PATH=C:\ProgramData\chocolatey\lib\ilmerge;%PATH%
before_build:
- ps: >-
    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);
    $trunk = "$rootLocation\trunk\Managed.AndroidDebugBridge";
    $ignore = Set-Location $trunk;
    .\Build\InstallPfx.ps1 -pfx "$trunk\Shared\madb.pfx" -password ((Get-Item Env:\MADB_PFX_KEY).Value) -containerName ((Get-Item Env:\VS_PFX_KEY).Value);
    $ignore = Set-Location ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);
build:
  project: trunk\Managed.AndroidDebugBridge\Build\BuildAll.msbuild
  verbosity: detailed
after_build:
- ps: >-
    $version = (Get-Content -Path $trunk\Shared\VersionAssemblyInfo.txt);
    $env:MADB_BUILD_VERSION = $version;
artifacts:
- path: '**\Managed.Adb.*.zip'
  name: Zips
- path: '**\Managed.Adb.*.nupkg'
  name: Nupkg
deploy:
- provider: GitHub
  tag: $(APPVEYOR_PROJECT_NAME)-v$(MADB_BUILD_VERSION)
  release: $(APPVEYOR_PROJECT_NAME)-v$(MADB_BUILD_VERSION)
  auth_token:
    secure: UEgy2H9zJKLi599QoO3qVf5BKFqloRQ246ez9cEgsfV3vooAUfVopMS9+IjRtArL
  artifact: Zips
  draft: false
- provider: NuGet
  api_key:
    secure: /M57OlSjcpugJFARA+j30alG5I+J1QxfRCDi5lWU3YhhzE1kxqLiAxtO+Bu7bQJt
  artifact: Nupkg