version: 2.0.{build}
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
environment:
  MADB_PFX_KEY:
    secure: FJBT+POuE4uUdLGJRsmNsw==
  VS_PFX_KEY:
    secure: LYUvBEhpB5ZzJT6ij5xnSQ4QoeasERP+iATMxhRqNhs=
install:
- cmd: >-
    choco install -y ilmerge

    set PATH=C:\ProgramData\chocolatey\lib\ilmerge;%PATH%
before_build:
- ps: >-
    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);

    $trunk = "$rootLocation\trunk\Managed.AndroidDebugBridge";

    $ignore = Set-Location $trunk;


    .\Build\appveyor.before-build.ps1


    $ignore = Set-Location $rootLocation;
build:
  project: trunk\Managed.AndroidDebugBridge\Build\BuildAll.msbuild
  verbosity: detailed
after_build:
- ps: >-
    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);

    $trunk = "$rootLocation\trunk\Managed.AndroidDebugBridge";

    $ignore = Set-Location $trunk;


    .\Build\appveyor.after-build.ps1


    $ignore = Set-Location $rootLocation;
artifacts:
- path: '**\Managed.Adb.*.zip'
  name: Zips
- path: '**\Managed.Adb.*.nupkg'
  name: Nupkg
before_deploy:
- ps: >-
    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);

    $trunk = "$rootLocation\trunk\Managed.AndroidDebugBridge";

    $ignore = Set-Location $trunk;

    .\Build\appveyor.before-deployment.ps1

    $ignore = Set-Location $rootLocation;
deploy:
- provider: GitHub
  tag: $(APPVEYOR_PROJECT_NAME)-v$(MADB_BUILD_VERSION)
  release: $(APPVEYOR_PROJECT_NAME)-v$(MADB_BUILD_VERSION)
  auth_token:
    secure: UEgy2H9zJKLi599QoO3qVf5BKFqloRQ246ez9cEgsfV3vooAUfVopMS9+IjRtArL
  draft: true
  force_update: true
  on:
    branch: master
    CI_DEPLOY_GITHUB: True
- provider: NuGet
  api_key:
    secure: /M57OlSjcpugJFARA+j30alG5I+J1QxfRCDi5lWU3YhhzE1kxqLiAxtO+Bu7bQJt
  artifact: Nupkg
  on:
    branch: master
    CI_DEPLOY_NUGET: True
after_deploy:
- ps: >-
    $rootLocation = ((Get-Item Env:\APPVEYOR_BUILD_FOLDER).Value);

    $trunk = "$rootLocation\trunk\Managed.AndroidDebugBridge";

    $ignore = Set-Location $trunk;

    .\Build\appveyor.after-deployment.ps1

    $ignore = Set-Location $rootLocation;
notifications:
- provider: Slack
  auth_token:
    secure: dEyWFeGEKdMmajrfGAYOGhWPEpivj1DiWu1xbbngPVcDW8vucg7JvWtJWTdARJ2bLedEg009P1o0JupLLx69Fg==
  channel: notifications
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true